### ISSUE TITLE
New co-maintainer

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ban_ip#7]
I see that the current maintainer is seeking co-maintainers. I'm willing to do this.

PR to follow.

**Comment by bugfolder** [comment]
ping @docwilmot. I"m interested in working on the issues for this module (which I use), and also helping clean up the inconsistencies relative to `ip_blocking` module (see https://github.com/backdrop-contrib/ip_blocking/issues).

**Comment by docwilmot** [comment]
Done, sorry for the delay, fell off the radar.
